version: 2
jobs:
  build:
    working_directory: ~/greenfield
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: sleep 5 && npm test
      - run: npm run lint
