version: 2
jobs:
  build:
    working_directory: ~/greenfield
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run lint