version: 2
jobs:
  build:
    working_directory: /Users/stephen/hrgbld/fec/project-greenfield/greenfield/
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm test
